development:
  adapter: postgresql
  encoding: utf8
  database: houston_core_development
  host: <%= ENV.fetch("HOUSTON_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("HOUSTON_DB_PORT", 5432) %>
  prepared_statements: false

test:
  adapter: postgresql
  encoding: utf8
  database: houston_core_test
  host: <%= ENV.fetch("HOUSTON_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("HOUSTON_DB_PORT", 5432) %>
  prepared_statements: false

# Just so we can precompile assets locally
production:
  adapter: postgresql
  encoding: utf8
  database: houston_core_development
  host: <%= ENV.fetch("HOUSTON_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("HOUSTON_DB_PORT", 5432) %>
  prepared_statements: false
